// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJdatCcaTyJzaYEQxZJ_Sb9bbQbAjO70',
    appId: '1:344823340397:web:5613dead7566a7dc780e64',
    messagingSenderId: '344823340397',
    projectId: 'chatapp-f57da',
    authDomain: 'chatapp-f57da.firebaseapp.com',
    storageBucket: 'chatapp-f57da.appspot.com',
    measurementId: 'G-VXTZ8VZ6N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP-AsDgFaFqkH0B5-zXgwIbiiIlGv_Uvo',
    appId: '1:344823340397:android:7dadfb698b36d190780e64',
    messagingSenderId: '344823340397',
    projectId: 'chatapp-f57da',
    storageBucket: 'chatapp-f57da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHMK4jxNNH4jGaaTLcLJx96MH4WTCplaU',
    appId: '1:344823340397:ios:ddbb44ed2115505c780e64',
    messagingSenderId: '344823340397',
    projectId: 'chatapp-f57da',
    storageBucket: 'chatapp-f57da.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJdatCcaTyJzaYEQxZJ_Sb9bbQbAjO70',
    appId: '1:344823340397:web:48cb9eeffdd48faf780e64',
    messagingSenderId: '344823340397',
    projectId: 'chatapp-f57da',
    authDomain: 'chatapp-f57da.firebaseapp.com',
    storageBucket: 'chatapp-f57da.appspot.com',
    measurementId: 'G-2V1CLTXV43',
  );
}
